config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  get 'signup' => 'individual_users#new', as: :signup
  post 'signup' => 'individual_users#create'
  get 'profile' => 'individual_users#show', as: :profile
  get 'profile/edit' => 'individual_users#edit', as: :edit_profile
  patch 'profile' => 'individual_users#update'

  resources :users, except: [:show], as: :profiles
  get 'profiles/:username' => 'users#show'

  resources :pages, except: [:show]

  url = ":url1"
  get url => 'pages#show'
  m_url = Rails.application.config.max_url_length
  (2..m_url).each do |x|
    url += "/:url#{x}"
    get url => 'pages#show'
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :require_editor, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <h1>Editing article</h1>

  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Listing articles</h1>

  <%= link_to 'New article', new_article_path %>

  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>

    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article), method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>New Article</h1>

  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <p>
    <h3>Title:</h3>
    <%= @article.title %>
  </p>

  <p>
    <h3>Text</h3>
    <%= @article.text %>
  </p>

  <h2>Comments</h2>
  <%= render @article.comments %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>
</div>