config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  get 'signup' => 'individual_users#new', as: :signup
  post 'signup' => 'individual_users#create'
  get 'profile' => 'individual_users#show', as: :profile
  get 'profile/edit' => 'individual_users#edit', as: :edit_profile
  patch 'profile' => 'individual_users#update'

  resources :users, except: [:show], as: :profiles
  get 'profiles/:username' => 'users#show'

  resources :pages, except: [:show]

  url = ":url1"
  get url => 'pages#show'
  m_url = Rails.application.config.max_url_length
  (2..m_url).each do |x|
    url += "/:url#{x}"
    get url => 'pages#show'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :roles
  has_many :permissions, through: :roles
  accepts_nested_attributes_for :permissions

  has_secure_password

  validates :password, confirmation: true, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  def has_permission?(permission)
    !self.permissions.find_by(name: permission).nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  before_action :require_admin, except: [:show]

  include UsersHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @permissions = @user.permissions.pluck(:name).join(',')
  end

  def create
    @user = User.new(user_params)

    if @user.save

      params['permissions'].split(',').each do |x|
        puts "ADDING #{x} TO USER"
        @user.roles.create(permission: Permission.find_by(name: x))
      end
      
      if @user.save
        redirect_to '/'
      end
    else
      redirect_to profiles_path(@user)
    end
  end

  def show
    if current_user.username == params[:username]
      redirect_to profile_path
      return
    end
    @user = User.find_by(username: params[:username])
  end

  def edit
    @user = User.find_by(username: params[:id])
    @permissions = @user.permissions.pluck(:name).join(',')
  end

  def update
    @user = User.find_by(username: params[:id])
    @permissions = @user.permissions.pluck(:name).join(',')

    case params[:form_type]
    when 'general'
      params[:form_type] = nil
      if @user.update(general_params)
        redirect_to profiles_path(@user)
      else
        render 'edit'
      end
    when 'password'
      params[:form_type] = nil
      @current_user = User.find(session[:user_id])
      if @current_user.authenticate(params[:user][:current_password])
        if @user.update(password_params)
          redirect_to profiles_path(@user)
        else
          render 'edit'
        end
      else
        render 'edit'
      end
    when 'permissions'
      Role.delete(@user.role_ids)
      params['permissions'].split(',').each do |x|
        puts "ADDING #{x} TO USER"
        @user.roles.create(permission: Permission.find_by(name: x))
      end
      @user.save
      redirect_to profile_path
    else
      render 'edit'
    end
  end

  def destory
    @user = User.find_by(params[:username])
    @user.destroy

    redirect_to '/'
  end

  private
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :image, :password, :password_confirmation)
  end
  def general_params
    params.require(:user).permit(:email, :image, :permissions)
  end
  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def profiles_path(user=nil)
    if user.nil?
      "/users"
    else
      "/profiles/#{user.username}"
    end
  end

end

app/views/users/edit.html.erb
<div class="profile">
  <div class="container">

      <h1>Account</h1>

      <div class="form general_form">
        <%= form_for(@user, url: edit_profile_path(@user)) do |f| %>
          <h2>Update Account Info</h2>
          <%= f.email_field :email, :placeholder => "Email" %><br>
          <%= f.text_field :image, :placeholder => "Image" %><br>
          <input type="hidden" name="form_type" value="general">
          <%= f.submit "Update Info", class: "btn-submit" %>
        <% end %>
      </div>

      <% if current_user.has_permission?('admin') and current_user.username != @user.id %>
        <div class="form permissions_form">
          <%= form_for(@user, url: edit_profile_path(@user)) do |f| %>
            <h2>Change Permissions</h2>
            <%= text_field_tag(:permissions, @permissions) %><br>
            <input type="hidden" name="form_type" value="permissions">
            <%= submit_tag("Change Permissions", class: "btn-submit") %>
          <% end %>
        </div>
      <% end %>

      <div class="form password_form">
        <%= form_for(@user, url: edit_profile_path(@user)) do |f| %>
          <h2>Change Password</h2>
          <%= f.password_field :password, :placeholder => "New Password" %><br>
          <%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %><br>
          <br>
          <%= f.password_field :current_password, :placeholder => "Password" %><br>
          <input type="hidden" name="form_type" value="password">
          <%= f.submit "Change Password", class: "btn-submit" %>
        <% end %>
      </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Users</h1>

  <%= link_to 'New user', new_profile_path %>

  <table>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>

    <% @users.each do |user| %>
      <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <% if user.id == current_user.id %>
        <td><%= link_to 'Show', profile_path %></td>
    <% else %>
        <td><%= link_to 'Show', profiles_path(user) %></td>
    <% end %>
    </tr>
  <% end %>
  </table>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

      <h1>Create New Account</h1>

      <div class="form new_user_form">
        <%= form_for(@user, url: profiles_path) do |f| %>
          <h2>Account Info</h2>
          <%= f.text_field :username, :placeholder => "Username" %><br>
          <%= f.email_field :email, :placeholder => "Email" %><br>
          <%= f.text_field :image, :placeholder => "Image" %><br>
            <%= text_field_tag(:permissions, @permissions) %><br>
          <%= f.password_field :password, :placeholder => "New Password" %><br>
          <%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %><br>
          <%= f.submit "Create User", class: "btn-submit" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile">
  <div class="container">

      <h1>Account Info</h1>

      <% unless @user.image.nil? %>
        <%= image_tag @user.image %>
      <% end %>
      <%= @user.username %><br>
      <%= @user.first_name %>
      <%= @user.last_name %><br>
      <%= @user.email %><br>
      <%= link_to "Edit", edit_profile_path(@user) %>

  </div>
</div>