config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  get 'signup' => 'individual_users#new', as: :signup
  post 'signup' => 'individual_users#create'
  get 'profile' => 'individual_users#show', as: :profile
  get 'profile/edit' => 'individual_users#edit', as: :edit_profile
  patch 'profile' => 'individual_users#update'

  resources :users, except: [:show], as: :profiles
  get 'profiles/:username' => 'users#show'

  resources :pages, except: [:show]

  url = ":url1"
  get url => 'pages#show'
  m_url = Rails.application.config.max_url_length
  (2..m_url).each do |x|
    url += "/:url#{x}"
    get url => 'pages#show'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>J4rj</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <header>
      <nav>
        <div class="nav-left">
          <div class="expand">
            <%= link_to raw('<div class="title">Home</div>'), '/' %>
            <div class="content myhide">
              <%= link_to raw('<div class="item">Articles</div>'), controller: 'articles' %>
              <% if current_user %>
                <% if current_user.has_permission?('admin') %>
                  <%= link_to raw('<div class="item">Users</div>'), profiles_path %>
                  <%= link_to raw('<div class="item">New user</div>'), new_profile_path %>
                <% end %>
                <% if current_user.has_permission?('editor') %>
                  <%= link_to raw('<div class="item">New page</div>'), new_page_path %>
                  <%= link_to raw('<div class="item">New article</div>'), new_article_path %>
                  <% unless @page.nil? %>
                    <% unless @page.id.nil? %>
                      <%= link_to raw('<div class="item">Edit page</div>'), edit_page_path(@page) %>
                    <% end %>
                  <% end %>
                  <% unless @article.nil? %>
                    <% unless @article.id.nil? %>
                      <%= link_to raw('<div class="item">Edit article</div>'), edit_article_path %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div><%= raw(serve_dropdown) %>
          <div class="link"><a href=""><div class="title">></div></a></div>
          <div class="link">
            <% if not @page.nil? %>
              <% unless @page.title.nil? %>
                <%= link_to raw("<div class=\"title\">#{@page.title}</div>"), '' %>
              <% else %>
                <%= link_to raw("<div class=\"title\">New Page</div>"), '' %>
              <% end %>
            <% elsif not @pages.nil? %>
              <%= link_to raw("<div class=\"title\">Pages</div>"), '' %>
            <% elsif not @article.nil? %>
              <% unless @article.title.nil? %>
                <%= link_to raw("<div class=\"title\">#{@article.title}</div>"), '' %>
              <% else %>
                <%= link_to raw("<div class=\"title\">New Article</div>"), '' %>
              <% end %>
            <% elsif not @articles.nil? %>
              <%= link_to raw("<div class=\"title\">Articles</div>"), '' %>
            <% elsif not @user.nil? %>
              <% unless @user.username.nil? %>
                <%= link_to raw("<div class=\"title\">#{@user.username}</div>"), '' %>
              <% else %>
                <%= link_to raw("<div class=\"title\">New User</div>"), '' %>
              <% end %>
            <% elsif not @users.nil? %>
              <%= link_to raw("<div class=\"title\">Users</div>"), '' %>
            <% elsif not @login.nil? %>
              <%= link_to raw("<div class=\"title\">Login</div>"), '' %>
            <% elsif not @home.nil? %>
              <%= link_to raw("<div class=\"title\">Home</div>"), '' %>
            <% end %>
          </div>
        </div>
        <div class="nav-right">
          <% if current_user %>
            <div class="expand">
              <%= link_to raw('<div class="title">My Account</div>'), profile_path %>
              <div class="content myhide">
                <%= link_to raw('<div class="item">Logout</div>'), logout_path %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="link">
            <%= link_to raw('<div class="title">Signup</div>'), signup_path %>
          </div><div class="link">
            <%= link_to raw('<div class="title">Login</div>'), login_path %>
          </div>
        <% end %>
      </nav>
    </header>
    
    <div class="wrapper">
      <%= yield %>
    </div>

    <footer>
      <div class="centered">
        Copyright &copy; Riley Trautman 2015
      </div>
    </footer>

  </body>
</html>